"use strict";
const stage=document.querySelector('#stage'),gift=document.querySelector('#gift'),drum=document.querySelector('#drum'),ending=document.querySelector('#ending'),sound=document.querySelector('#sound'),canvas=document.querySelector('#confetti'),burst=document.querySelector('#burst');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let state='gift',muted=false,ctx,master,noise,raf=0,fxRaf=0;
const setState=value=>{state=value;stage.dataset.state=value};
async function unlockAudio(){try{if(!ctx){ctx=new(window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=muted?0:.55;const compressor=ctx.createDynamicsCompressor();master.connect(compressor);compressor.connect(ctx.destination);noise=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate);const d=noise.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1}await Promise.race([ctx.resume(),new Promise(resolve=>setTimeout(resolve,250))])}catch{/* Visual flow remains usable without audio. */}}
function snare(at,level,pan=0){if(!ctx)return;const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();source.buffer=noise;filter.type='highpass';filter.frequency.value=1100;gain.gain.setValueAtTime(level,at);gain.gain.exponentialRampToValueAtTime(.001,at+.09);source.connect(filter);filter.connect(gain);if(ctx.createStereoPanner){const p=ctx.createStereoPanner();p.pan.value=pan;gain.connect(p);p.connect(master)}else gain.connect(master);source.start(at,Math.random()*.7);source.stop(at+.11);const body=ctx.createOscillator(),bodyGain=ctx.createGain();body.type='triangle';body.frequency.setValueAtTime(185,at);body.frequency.exponentialRampToValueAtTime(110,at+.06);bodyGain.gain.setValueAtTime(level*.4,at);bodyGain.gain.exponentialRampToValueAtTime(.001,at+.085);body.connect(bodyGain);bodyGain.connect(master);body.start(at);body.stop(at+.1)}
function roll(seconds,orbit){if(!ctx||ctx.state!=='running')return;const base=ctx.currentTime+.025;let t=0,i=0;while(t<seconds-.16){const f=t/seconds;snare(base+t,.13+f*.2+(i%2)*.025,orbit?Math.sin(f*Math.PI*6)*.8:0);t+=.1-f*.065;i++}}
function bang(){if(!ctx||ctx.state!=='running')return;const at=ctx.currentTime;const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();source.buffer=noise;filter.type='highpass';filter.frequency.value=2400;gain.gain.setValueAtTime(.7,at);gain.gain.exponentialRampToValueAtTime(.001,at+.8);source.connect(filter);filter.connect(gain);gain.connect(master);source.start(at);source.stop(at+.85);const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.setValueAtTime(135,at);o.frequency.exponentialRampToValueAtTime(40,at+.25);g.gain.setValueAtTime(.7,at);g.gain.exponentialRampToValueAtTime(.001,at+.4);o.connect(g);g.connect(master);o.start(at);o.stop(at+.42)}
function confetti(){cancelAnimationFrame(fxRaf);const dpr=Math.min(devicePixelRatio||1,2),w=stage.clientWidth,h=stage.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);const colors=['#ed2445','#ffbf36','#517aff','#af51ff','#12cfa7','#ff79ba'];const pieces=Array.from({length:reduced?30:210},()=>({x:w/2,y:h*.47,vx:(Math.random()-.5)*22,vy:-6-Math.random()*17,r:Math.random()*Math.PI,s:5+Math.random()*7,c:colors[Math.floor(Math.random()*colors.length)]}));let prev=performance.now(),elapsed=0;const duration=reduced?900:2800;function frame(now){const dt=Math.min((now-prev)/16.67,2);prev=now;elapsed+=dt*16.67;c.clearRect(0,0,w,h);for(const p of pieces){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=.28*dt;p.vx*=.995;p.r+=.09*dt;c.globalAlpha=Math.max(0,Math.min(1,(duration-elapsed)/600));c.save();c.translate(p.x,p.y);c.rotate(p.r);c.fillStyle=p.c;c.fillRect(-p.s/2,-p.s/2,p.s,p.s*.55);c.restore()}if(elapsed<duration)fxRaf=requestAnimationFrame(frame);else c.clearRect(0,0,w,h)}fxRaf=requestAnimationFrame(frame)}
function explode(){bang();burst.classList.remove('pop');void burst.offsetWidth;burst.classList.add('pop');confetti()}
const trail=document.querySelector('#trail');
const trailWords=['어떤','문의가','왔을','까요','궁금','하시죠','~?'];
function orbitPoint(t){const w=stage.clientWidth,h=stage.clientHeight,size=drum.clientWidth;const rx=Math.max(0,(w-size)/2-12),ry=Math.max(0,(h-size)/2-18);const travel=Math.min(1,t/.08);const turns=t<=.8?Math.max(0,(t-.08)/.72):1+(t-.8)/.16;const angle=-Math.PI/2+turns*Math.PI*2;const cos=Math.cos(angle),sin=Math.sin(angle);const home=t>.94?(1-t)/.06:1;return{x:rx*Math.sign(cos)*Math.pow(Math.abs(cos),.35)*travel*home,y:ry*Math.sign(sin)*Math.pow(Math.abs(sin),.35)*travel*home}}
function stampWord(index,at){const p=orbitPoint(at),word=document.createElement('span');word.className='trail-word';word.textContent=trailWords[index];word.style.left=`${stage.clientWidth/2+p.x}px`;word.style.top=`${stage.clientHeight/2+p.y}px`;word.style.setProperty('--tilt',`${index%2?5:-5}deg`);trail.append(word)}
function animateRoll(round,duration){return new Promise(resolve=>{const start=performance.now();let stamped=0;trail.replaceChildren();trail.hidden=false;const step=now=>{const t=Math.min(1,(now-start)/duration);while(stamped<trailWords.length&&t>=.1+stamped*.1+.035){stampWord(stamped,.1+stamped*.1);stamped++}const p=orbitPoint(t),x=reduced?0:p.x,y=reduced?0:p.y,rotation=reduced?0:t*1080+Math.sin(t*duration*.12)*5,scale=reduced?1:.8+t*.3;drum.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px)) rotate(${rotation}deg) scale(${scale})`;if(t<1)raf=requestAnimationFrame(step);else{trail.hidden=true;resolve()}};raf=requestAnimationFrame(step)})}
async function startRound(){if(state!=='gift')return {error:'지금은 실행할 수 없습니다.'};setState('rolling');gift.disabled=true;gift.hidden=true;drum.hidden=false;drum.style.transform='translate(-50%,-50%)';await unlockAudio();const duration=6100;roll(duration/1000,true);await animateRoll(2,duration);drum.hidden=true;explode();await new Promise(r=>setTimeout(r,360));ending.hidden=false;setState('ending');ending.querySelector('h2').focus({preventScroll:true});return {state,result:'넵.'}}
gift.addEventListener('click',startRound);sound.addEventListener('click',()=>{muted=!muted;sound.setAttribute('aria-pressed',String(muted));sound.setAttribute('aria-label',muted?'소리 켜기':'소리 끄기');if(master)master.gain.setTargetAtTime(muted?0:.55,ctx.currentTime,.025)});
const lifecycle=new AbortController();if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'open_gift',title:'선물상자 열기',description:'선물상자를 열고 화면 가장자리를 도는 북 연출 이후 결과를 표시합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(input===null||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('입력은 빈 객체여야 합니다.');return startRound()}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}window.addEventListener('pagehide',()=>{lifecycle.abort();cancelAnimationFrame(raf);cancelAnimationFrame(fxRaf);if(ctx)ctx.close().catch(()=>{})},{once:true});
